@host=https://localhost:7050

POST {{host}}/auth/register
Content-Type: application/json

{
"firstName": "Iliyan",
"lastName": "Tsvetkov",
"username": "iliyantsvetkov",
"email": "asjmasssac@gmail.com",
"password": "abigsecretpasswordguy123"
}

