@host=https://localhost:7050
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzYwZDczMi1mMDA5LTQwNDItYTA1Yy0yM2E3ZDJiYTdlMTkiLCJnaXZlbl9uYW1lIjoiSWxpeWFuIiwiZmFtaWx5X25hbWUiOiJUc3ZldGtvdiIsImp0aSI6ImUwZjM3M2E5LTdkZDMtNDhiMi05ZWU5LTg3OGFmNTRlZmM5MCIsImV4cCI6MTY4NjY4MTA1NiwiaXNzIjoiRm9ydW1Qcm9qZWN0IiwiYXVkIjoiRm9ydW1Qcm9qZWN0In0.KcaB4kILJRdvp7ePDcluEzvr2XHjnEdDD3d8TgItSWY
POST {{host}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "aASD",
    "content": "ASDASDASD"
}
