@host=https://localhost:7050

GET {{host}}/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjZiZDQwZS02MzJkLTQyMjAtYTc3Yi05MWQ4NDAwODY0NDciLCJnaXZlbl9uYW1lIjoiSmFtZXMiLCJmYW1pbHlfbmFtZSI6Ik1jQXZveSIsImp0aSI6IjNjOGM0ZmUwLTE5YTktNDAwMi05NjA1LWQ1YzM5ZWQzMThhYSIsInVuaXF1ZV9uYW1lIjoiNzEyMTk4NDctMzk3Yy00N2MyLTgwMGMtODJjOWE0ZmJmNDc3IiwiZXhwIjoxNjg2NTI0NDc4LCJpc3MiOiJGb3J1bVByb2plY3QiLCJhdWQiOiJGb3J1bVByb2plY3QifQ.0jiOVHNLNb3xE_kgPojYx9cT6oTy5I0U-roFD4rFx9s